services:
    db:
        container_name: db
        image: mcr.microsoft.com/mssql/server:2022-latest
        restart: unless-stopped
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "P@ssword1"
        ports:
            - 1433:1433
        volumes:
            - db-data:/var/opt/mssql

volumes:
    db-data:
        